name: Reusable action of Release preparation

on: 
  workflow_call:
    secrets:
      CI_USER_TOKEN:
        required: true
    inputs:
      VERSION:
        required: true
        type: number

jobs:
  prepare_for_release:
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
    - uses: actions/checkout@v3
      with:
        xcode-version: '12.4'
    - id: prepare_for_release
      name: Prepare for release
      env:
        VERSION: ${{ inputs.VERSION }}
        HOME: 'home/runner'
        REPO_SLUG: ${{ github.repository }}
        BRANCH: ${{ github.ref_name }}
        GITHUB_USER: optibot
        GITHUB_TOKEN: ${{ secrets.CI_USER_TOKEN }}
      run: |
        gem install cocoapods -v '1.9.3'
        Scripts/run_prep.sh
    - name: Check prepare for release failure
      if: steps.prepare_for_release.conclusion == 'failure'
      run: cat /tmp/build.out
