name: Reusable action of Preparing for release

on:
  workflow_call:
    secrets:
      CI_USER_TOKEN:
        required: true

jobs:
  prepare_for_release: 
    runs-on: macos-latest
    steps:
    - name: set SDK Branch if PR
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        echo "SDK_BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV
        echo "TRAVIS_BRANCH=${{ github.base_ref }}" >> $GITHUB_ENV
    - name: set SDK Branch if not pull request
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        echo "SDK_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
        echo "TRAVIS_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
    - uses: maxim-lobanov/setup-xcode@v1
    - uses: actions/checkout@v3
      with:
        xcode-version: '12.4'
    - id: prepare_for_release
      name: Prepare for release
      env:
        VERSION: 3.10.1
        HOME: 'home/runner'
        TRAVIS_REPO_SLUG: ${{ github.repository }}
        GITHUB_USER: optibot
        GITHUB_TOKEN: ${{ secrets.CI_USER_TOKEN }}
      run: |
        gem install cocoapods -v '1.9.3'
        Scripts/run_prep.sh
    - name: Check prepare for release failure
      if: steps.prepare_for_release.outcome != 'success'
      run: cat /tmp/build.out