name: Swift

on:
  push:
    branches: [ master, 'release/**' ]
  pull_request:
    branches: [ master, 'release/**' ]
  workflow_dispatch:

permissions:
  contents: read

jobs:

  lint_markdown_files:
    uses: optimizely/swift-sdk/.github/workflows/lint_markdown.yml@master

  integration_tests:
    uses: optimizely/swift-sdk/.github/workflows/integration_tests.yml@master
    secrets:
      CI_USER_TOKEN: ${{ secrets.CI_USER_TOKEN }}

  package_validation:
    runs-on: xcode-27
    steps:
    - uses: actions/checkout@v3
    - env:
        SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
      run: |
        swift package resolve
        swift build
        curl -sSL https://download.sourceclear.com/ci.sh | bash

  unittests:
    uses: ./.github/workflows/unit_tests.yml
