name: Jira ticket reference check

on:
  pull_request:
     types: [opened, edited, reopened, synchronize]

jobs:

  jira_ticket_reference_check:
    runs-on: ubuntu-latest

    steps:
      - name: Check for Jira ticket reference
        uses: optimizely/github-action-ticket-reference-checker-public@06871091b2c0e23c0354109a29406bc0e47f6af1 # master
        with:
          bodyRegex: 'FSSDK-(?<ticketNumber>\d+)' 
